### ISSUE TITLE
Question: how to do cross compile?

### ISSUE THREAD

**Issue by kokizzu** [mutecomm/go-sqlcipher#1]
I've tried:

```
env GOOS=linux GOARCH=amd64 go build 
```

but it shows:

```
go build github.com/mutecomm/go-sqlcipher: no buildable Go source files in /Users/asd/MEGA/go/src/github.com/mutecomm/go-sqlcipher
```

OS: Mac OSX latest
Arch: amd64

but it works fine if not using `mutecomm/go-sqlcipher`

**Comment by frankbraun** [comment]
As far as I know cross-compiling Go code which uses cgo doesn't work in Go, see https://golang.org/cmd/cgo/
