### ISSUE TITLE
Any updates on KDF algo itr, HMAC algo and KDF algo

### ISSUE THREAD

**Issue by akjhacse** [mutecomm/go-sqlcipher#10]
Can you please let me the value of KDF itereations , HMAC algo used and KDF algo used. If page size is 4096

**Comment by akjhacse** [comment]
I want to decrypt it using sqlite browser studio

**Comment by frankbraun** [comment]
I use the default values from SQLCipher as described for example here: https://www.zetetic.net/sqlcipher/design/

This seems to be a sqlite browser studio question or SQLCipher, nothing related to this package.

**Comment by frankbraun** [comment]
```
PRAGMA cipher_page_size = 1024;
PRAGMA kdf_iter = 64000;
PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1;
```

From: https://discuss.zetetic.net/t/upgrading-to-sqlcipher-4/3283
