### ISSUE TITLE
Concurrency

### ISSUE THREAD

**Issue by FabianTe** [mutecomm/go-sqlcipher#11]
Hi, thanks for this nice module, I had trouble using other sqlite encryption modules, this simply works.

One question: Is the package safe to be used by multiple goroutines? i. e.: I use the sqlite file as the database for a small webservice that could potentially handle many requests at once. Therefore I have to assume that database writes may happen concurrently.

Thanks in advance

**Comment by frankbraun** [comment]
Yes, the package is thread-safe. 

https://golang.org/pkg/database/sql/#Open is inherently thread-safe.

See also the discussion https://github.com/mattn/go-sqlite3/issues/249 for more details
