### ISSUE TITLE
File is not a database on query

### ISSUE THREAD

**Issue by hazcod** [mutecomm/go-sqlcipher#21]
Hi,

I am trying to write a commandline client for Enpass 6.x password vaults.
These are stored on regular sqlite databases as attached. [enpassvault.zip](https://github.com/mutecomm/go-sqlcipher/files/5651584/enpassvault.zip)

However, every query will return `file is not a database` while the [Python version](https://github.com/hazcod/enpass-cli/issues/16#issuecomment-738892278) seems to work fine.
Any idea?

https://github.com/hazcod/enpass-cli-test

```go
% go run main.go 
2020/12/07 09:55:14 printing tables
2020/12/07 09:55:15 could not retrieve crypto parameters: could not query crypto parameters: file is not a database
exit status 1
```

**Comment by jmastr** [comment]
Issue was that we tried to open an SQLCipher 3.x DB with go-sqlcipher 4.x and it's not compatible. I think the issue can be closed.
