### ISSUE TITLE
Database re-encrypts after a minute or so

### ISSUE THREAD

**Issue by cpacia** [mutecomm/go-sqlcipher#6]
Question.

I'm currently doing something like this:
```
conn, err := sql.Open("sqlite3", dbPath)
if err != nil {
	return nil, err
}
if password != "" {
	p := "pragma key='" + password + "';"
	conn.Exec(p)
}
```
Immediately following this code I query to check to see if the db decrypted properly and it does. But then a minute or so later I start getting a `file is encrypted or is not a database` error. I'm not closing the connection. Just making queries on the existing instance. 

Am I using this wrong? Is there some kind of timeout that re-encrypts it shortly after decryption? Do I need to re-call `pragma key=` before each db query?

**Comment by frankbraun** [comment]
No, that should be fine. Please compare your code to the examples in https://github.com/mutecomm/go-sqlcipher/blob/master/sqlcipher_test.go

Do you use "database/sql" or do you use another abstraction layer on top that might open up a separate connection which is then not decrypted?

If possible, could you create a minimal example (like the ones in the test file) that reproduces your problem? I have never seen your problem and I have no idea how I would go about reproducing it.

**Comment by frankbraun** [comment]
Since I didn't hear back I'm closing this issue. Please reopen if the problem is reproducible.
