### ISSUE TITLE
Upgrade SQLCipher

### ISSUE THREAD

**Issue by someblue** [mutecomm/go-sqlcipher#7]
Hi, @frankbraun , thanks for your awesome library!

A newer version of SQLite and SQLCipher has been released. Could you upgrade it to latest version?

**Comment by frankbraun** [comment]
I updated to SQLCipher v3.4.2, the latest release of the 3.x branch. Upgrading to 4.x would require major changes to go-sqlcipher which include adding more C functions needed by SQLCipher 4.x (to stay self-contained) and working out an upgrade plan for existing consumers (4.x is incompatible to 3.x).

I cannot commit to that right now.

**Comment by someblue** [comment]
Thanks very much!

Would you upgrade to 4.x in future?

**Comment by frankbraun** [comment]
I just upgraded to 4.4.0. Please see [Incompatibilities of SQLCipher](https://github.com/mutecomm/go-sqlcipher#incompatibilities-of-sqlcipher) on how to upgrade.
