### ISSUE TITLE
Question: Do you have a plan to update codes from mattn/go-sqlite3?

### ISSUE THREAD

**Issue by deepinstar** [mutecomm/go-sqlcipher#8]
Do you have a plan to update codes from mattn/go-sqlite3?

I wanna use this method.
```go
// from mattn/go-sqlite3
func (c *SQLiteConn) RegisterFunc(name string, impl interface{}, pure bool) error
```
https://github.com/mattn/go-sqlite3/blob/2a192bf7823799e082cfa3380aab9f02e4d312c0/sqlite3.go#L551

**Comment by frankbraun** [comment]
I just upgraded go-sqlcipher to the latest version of go-sqlite3 (see referenced commit). Could you try that?

**Comment by frankbraun** [comment]
This is part of go-sqlcipher now, closing the issue.
